// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDataFromFiles(arg1, arg2) {
  return window['go']['file_services']['FileService']['ListDataFromFiles'](arg1, arg2);
}

export function ListFiles(arg1, arg2) {
  return window['go']['file_services']['FileService']['ListFiles'](arg1, arg2);
}
