// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectFile() {
  return window['go']['file_services']['FilePicker']['SelectFile']();
}

export function WailsInit(arg1) {
  return window['go']['file_services']['FilePicker']['WailsInit'](arg1);
}
