// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindFileFromFilePathEnumIfExistsAndReturnEncoded(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function ListDataFromFilePath(arg1:string):Promise<Array<string>>;

export function ListDataFromFilePathEnum(arg1:string,arg2:string):Promise<Array<string>>;

export function ListFiles(arg1:string,arg2:boolean):Promise<Array<string>>;
