// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindFileFromFilePathEnumIfExistsAndReturnEncoded(arg1, arg2, arg3, arg4) {
  return window['go']['file_services']['FileService']['FindFileFromFilePathEnumIfExistsAndReturnEncoded'](arg1, arg2, arg3, arg4);
}

export function ListDataFromAllFiles(arg1) {
  return window['go']['file_services']['FileService']['ListDataFromAllFiles'](arg1);
}

export function ListDataFromFilePath(arg1) {
  return window['go']['file_services']['FileService']['ListDataFromFilePath'](arg1);
}

export function ListDataFromFilePathEnum(arg1, arg2) {
  return window['go']['file_services']['FileService']['ListDataFromFilePathEnum'](arg1, arg2);
}

export function ListFiles(arg1, arg2) {
  return window['go']['file_services']['FileService']['ListFiles'](arg1, arg2);
}

export function LoadAllAudioInDirectory(arg1, arg2, arg3) {
  return window['go']['file_services']['FileService']['LoadAllAudioInDirectory'](arg1, arg2, arg3);
}
